export const TEST  ='TEST';



export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FETCH_QUESTION = 'FETCH_QUESTION';

export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';


export const CHANGE_HANDLER = 'CHANGE_HANDLER';

export const SUBMIT = 'SUBMIT';

export const FETCH_USER = 'FETCH_USER';


export const CHANGE_ROUTE = 'CHANGE_ROUTE';

export const CLEAR_TOKEN = 'CLEAR_TOKEN';

export const SELECT_SUBJECT = 'SELECT_SUBJECT';


export const ERROR_LOGIN = 'ERROR_LOGIN';

export const DONE_EXAMMING = 'DONE_EXAMMING';

export const SET_EXAM_MATH = 'SET_EXAM_MATH';


export const FETCH_CORRECT = 'FETCH_CORRECT';


export const GET_USER_ID_KEY = 'GET_USER_ID_KEY';


export const SAVE_MARK_FROM_EXAMMING = 'SAVE_MARK_FROM_EXAMMING';


export const REDONE_EXAMMING = 'REDONE_EXAMMING';

export const DELETE_SUBJECT_STATE = 'DELETE_SUBJECT_STATE';

export const FETCH_QUESTION_LOADING = 'FETCH_QUESTION_LOADING';

export const RESULT_UNMOUNT_DELETE_SUBJECT_DONE = 'RESULT_UNMOUNT_DELETE_SUBJECT_DONE';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';


